services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

networks:
  default:
    name: planner-network